### ISSUE TITLE
Plugin is installed but did not work

### ISSUE THREAD

**Issue by rclabs-dev** [jellyfin/jellyfin-plugin-discogs#2]
Hello dear,

First, congratulations on the product, which is great.

So, I installed the DISCOGS plugin, but I don't know how to use it. It doesn't appear anywhere, except in the plugins area, which shows as active, with my correct DISCOGS account developer token, it show ias version 0.0.0.0, but nothing more than that.

I use Debian 12. I installed .NET for this version via APT as indicated by MS. I did "git clone" and inside the folder I executed the command "dotnet publish --configuration Release --output bin" which criticized the "--output bin" key, but created and placed all the files there, which I copy to the /var/lib/jellyfin/plugins/discogs folder and restart Jellyfin.

Did I do something wrong or is the plugin still not 100%?

Any debug tests I can do?

I apologize if this is not the channel for this type of question.

Thanks in advance.

Best regards,

Regivaldo Costa
![plugin02](https://github.com/jellyfin/jellyfin-plugin-discogs/assets/7923262/97d8f550-2dee-4b5b-8ec9-27e844870769)
![plugin01](https://github.com/jellyfin/jellyfin-plugin-discogs/assets/7923262/62e6e00e-8908-46ad-9f14-fdf98b77987f)
![plugin03](https://github.com/jellyfin/jellyfin-plugin-discogs/assets/7923262/02791be9-1020-405c-a861-35f3cca18d6e)

**Comment by nielsvanvelzen** [comment]
To use the plugin you need to do a few things:

1) Use 10.8.z. I have not tested it with 10.9 and I suspect it might not work there
2) Add the personal access token. It should work without it but it will be slower and never fetch images
3) Enable the metadata provider in your music library for albums & artists
4) Enable the image fetcher in your music library for albums & artists

**Comment by rclabs-dev** [comment]
![plugin04](https://github.com/jellyfin/jellyfin-plugin-discogs/assets/7923262/2003b6f9-7faf-4fcb-9876-53b8a4349750)
> To use the plugin you need to do a few things:
> 
> 1. Use 10.8.z. I have not tested it with 10.9 and I suspect it might not work there
> 2. Add the personal access token. It should work without it but it will be slower and never fetch images
> 3. Enable the metadata provider in your music library for albums & artists
> 4. Enable the image fetcher in your music library for albums & artists

Dear Niels Velzen,

Thank you very much for the quick help.

I'm using version 8.2.13 as screenshot below.

Yes, I am using personal token. As shown in the screenshot above, just replace some part with "-" to partially mask it.

At first, I thought the plugin's function would be to bring data from my collection to some area, but now I better understand how to associate the songs in the library with the metadata present in discogs, not just those in my collection.

I just didn't do the activations you indicated in items 3 and 4. I'll be doing that and checking the results.

One question, as shown in the image above, should the plugin version really appear as 0.0.0.0?

Congratulations and thank you very much.

Regards,

**Comment by crobibero** [comment]
> One question, as shown in the image above, should the plugin version really appear as 0.0.0.0?

Yes, until we create an official release it will say `0.0.0.0`

**Comment by rclabs-dev** [comment]
> > One question, as shown in the image above, should the plugin version really appear as 0.0.0.0?
> 
> Yes, until we create an official release it will say `0.0.0.0`

Dear,

Many thanks.

Regards,

Regivaldo Costa
--

**Comment by abrittaf** [comment]
Hi there!, I have same situation as Regivaldo. The plugin was installed and every checkpoints were made as you suggested. 
I also trying making it work using a personal token.
These log messages appear when I try to refresh metadata for a particular Album. I hope they help to find a fix for this issue. 

```
[09:05:48] [ERR] [40] MediaBrowser.Providers.Music.AlbumMetadataService: Error in Discogs
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.Discogs.DiscogsApi.Request(HttpRequestMessage request, CancellationToken cancellationToken) in /app/Jellyfin.Plugin.Discogs/DiscogsApi.cs:line 81
   at Jellyfin.Plugin.Discogs.DiscogsApi.GetRelease(String id, CancellationToken cancellationToken) in /app/Jellyfin.Plugin.Discogs/DiscogsApi.cs:line 97
   at Jellyfin.Plugin.Discogs.Providers.DiscogsAlbumProvider.GetMetadata(AlbumInfo info, CancellationToken cancellationToken) in /app/Jellyfin.Plugin.Discogs/Providers/DiscogsAlbumProvider.cs:line 80
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

Regards,
Fernando

**Comment by nielsvanvelzen** [comment]
@abrittaf please create a separate issue, as it is not the same situation. It might be a bug.

I'll also close this issue as solved.
